name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'  # Use the version you need

    - name: Install dependencies
      run: |
        flutter pub get
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev  # Install required dependencies

    - name: Run Flutter doctor
      run: flutter doctor

    - name: Build Flutter app
      run: flutter build apk  # or flutter build web, flutter build ios, etc.
