name: Flutter CI

on:
  push:
    branches: 
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches: 
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest checkout version

    - name: Set up JDK
      uses: actions/setup-java@v3  # Updated to the latest Java setup version
      with:
        java-version: '11'  # Specify the JDK version
        distribution: 'temurin'  # Specify the JDK distribution (use 'adopt' or 'zulu' if preferred)

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable  # Clone Flutter SDK
        echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH  # Add Flutter to PATH

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev  # Install missing dependencies

    - name: Get Flutter dependencies
      run: flutter pub get  # Get dependencies specified in pubspec.yaml

    - name: Run Flutter tests
      run: flutter test  # Run unit tests

    - name: Build the app
      run: flutter build apk  # Change this to flutter build web, flutter build linux, etc., as needed

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3  # Updated to the latest upload-artifact version
      with:
        name: flutter-build
        path: build/app/outputs/apk/release/app-release.apk  # Adjust the path based on your build type
